version: "3"
services:
    # Layanan PHP-FPM untuk Laravel
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

    # Layanan web server Nginx
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - php-fpm
        networks:
            - laravel-network

    # Layanan basis data MySQL
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: your-root-password
            MYSQL_DATABASE: your-database-name
            MYSQL_USER: your-username
            MYSQL_PASSWORD: your-password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:

volumes:
    mysql-data:
